-- Homescreen module schema.
--
-- The main server owns homescreens. Three sources can serve a profile's home:
--   1. custom  - authored by the user (via their own PAT on PUT /home)
--   2. reco    - generated by the external recommendation engine
--   3. default - built from TMDB by the main server, cached per locale
--
-- The default home is shared across profiles (per locale/region) and refreshed
-- on a schedule; the per-profile "continue watching" rail is layered on top at
-- request time so it never needs to live in the shared cached snapshot.

CREATE SCHEMA IF NOT EXISTS homescreen;

-- Ordered list of section providers that make up a home for a locale.
-- Only one template per locale may be active (enforced by partial index).
CREATE TABLE IF NOT EXISTS homescreen.templates (
  key text NOT NULL,
  locale text NOT NULL,
  title text,
  section_keys text[] NOT NULL,
  is_active boolean NOT NULL DEFAULT false,
  updated_by text NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (key, locale)
);

CREATE UNIQUE INDEX IF NOT EXISTS homescreen_templates_active_per_locale_uidx
  ON homescreen.templates (locale)
  WHERE is_active;

-- Curated collections (Harry Potter, MCU, trakt-imported popular lists, etc.).
-- Resolved to cards via providerRefs (e.g. {provider:'tmdb', providerId:'671'}).
CREATE TABLE IF NOT EXISTS homescreen.collections (
  key text PRIMARY KEY,
  title text NOT NULL,
  subtitle text,
  provider_refs jsonb NOT NULL,
  source text NOT NULL DEFAULT 'manual',
  source_ref text,
  last_synced_at timestamptz,
  updated_by text NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT homescreen_collections_source_chk
    CHECK (source IN ('manual', 'trakt'))
);

CREATE INDEX IF NOT EXISTS homescreen_collections_source_idx
  ON homescreen.collections (source, source_ref);

-- Definitions for pulling PUBLIC trakt lists into the collections registry.
CREATE TABLE IF NOT EXISTS homescreen.trakt_imports (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  trakt_list_id text,
  slug text NOT NULL,
  title text,
  template_key text NOT NULL,
  active boolean NOT NULL DEFAULT true,
  last_synced_at timestamptz,
  last_error text,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT homescreen_trakt_imports_slug_uniq UNIQUE (slug)
);

-- Cached default home per locale (profile-independent rails only).
-- Mirrored into Redis with a TTL; last_error surfaces refresh failures in admin.
CREATE TABLE IF NOT EXISTS homescreen.default_snapshots (
  locale text PRIMARY KEY,
  sections jsonb NOT NULL,
  generated_at timestamptz NOT NULL,
  expires_at timestamptz,
  last_error text,
  updated_by text,
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Seed a minimal global fallback template so a brand new locale still renders.
INSERT INTO homescreen.templates (key, locale, title, section_keys, is_active, updated_by)
VALUES ('default', 'all', 'Default', ARRAY[
  'tmdb-trending-hero',
  'tmdb-trending-movies',
  'tmdb-popular-movies',
  'tmdb-popular-tv'
], true, 'seed')
ON CONFLICT (key, locale) DO NOTHING;
