ALTER TABLE profile_title_metadata_state RENAME TO profile_tracked_title_state;

ALTER INDEX IF EXISTS profile_title_metadata_state_profile_media_key_idx
  RENAME TO profile_tracked_title_state_profile_media_key_idx;

ALTER INDEX IF EXISTS profile_title_metadata_state_profile_next_air_idx
  RENAME TO profile_tracked_title_state_profile_next_air_idx;
