export const PUBLIC_ACCOUNT_WRITE_SOURCE = 'account_api' as const;
export const PUBLIC_ACCOUNT_WRITE_IDEMPOTENCY_TTL_MS = 24 * 60 * 60 * 1000;
export const PUBLIC_ACCOUNT_WRITE_MAX_IDEMPOTENCY_KEY_LENGTH = 128;
